### ISSUE TITLE
Implement more robust database backups

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode_infra#10]

**Comment by ohaiwalt** [comment]
The production OpCode db is currently in a container in Kubernetes. While this is super neat, it makes things a bit tricky in terms of backups.

Given the level of time that volunteers have to allocate to maintaining the infrastructure, putting the database in AWS RDS greatly reduces the maintenance burden, and will likely be more reliable.

**Comment by ohaiwalt** [comment]
Blocked by #15 

After the DB is in RDS, ensure automatic backups are being taken daily.

**Comment by sethbergman** [comment]
Possible solution:
__CockroachDB__
Connecting to the CockroachDB cluster

Once you've created the cluster, you can start talking to it it by connecting to its "public" service. CockroachDB is PostgreSQL wire protocol compatible so there's a wide variety of supported clients.

### Failover

If any CockroachDB member fails it gets restarted or recreated automatically by the Kubernetes infrastructure, and will rejoin the cluster automatically when it comes back up.

https://kubeapps.com/charts/stable/cockroachdb

**Comment by nellshamrell** [comment]
The prod db is now in RDS - let's verify that the backups are happening.

**Comment by ohaiwalt** [comment]
Daily snapshots are happening now.
