### ISSUE TITLE
Delegate subdomain from operationcode.org domain to Route53

### ISSUE THREAD

**Issue by ohaiwalt** [OperationCode/operationcode_infra#14]
# Problem

The `operationcode.org` hosted zone is with DNSimple, and in order to use kops to create a Kubernetes cluster it needs to have control over its DNS records.

# Solution

Delegate a subdomain to Route 53 in order to provide kubernetes and kops with the ability to manage DNS records for its purposes.

**Comment by hollomancer** [comment]
@ohaiwalt, does this replace #2?

**Comment by ohaiwalt** [comment]
@hollomancer This is a prelude to #2 in order to get the k8s cluster up. That issue may prove unnecessary.

**Comment by ohaiwalt** [comment]
I have created a Route 53 hosted zone for `k8s.operationcode.org`, which creates NS records and an SOA record for that hosted zone. Those NS records are then also created in the `operationcode.org` hosted zone in DNSimple as the `k8s` NS record, which results in delegating responsibility for any subdomains of `k8s.operationcode.org` to the Route 53 hosted zone.

[Here](http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/CreatingNewSubdomain.html) is some relevant documentation.
