### ISSUE TITLE
Update master branch to main

### ISSUE THREAD

**Issue by irvingpop** [OperationCode/operationcode_infra#160]
These instructions should do the trick: https://dev.to/afrodevgirl/replacing-master-with-main-in-github-2fjf

We'll probably need to fix ArgoCD after the change to monitor the new branch

**Comment by projectLewis** [comment]
I do not believe I have privileges to do `step 2` in the link since I cant see `branches` in the settings. As such I havent done step one either.

We may be safe on ArgoCD since its tracking `HEAD` instead of a branch name. Im double checking this bit though.

**Comment by projectLewis** [comment]
Changed branch to `main`, have a PR open to verify everything is good with argoCD. We had to make a new key in circleCI. Once the test is good, I'll delete `master` branch completely.
