### ISSUE TITLE
Upgrade our EKS cluster to k8s 1.16

### ISSUE THREAD

**Issue by irvingpop** [OperationCode/operationcode_infra#161]
EKS 1.16 is out, we should probably upgrade to it

1. Grab the latest version of eksctl on your workstation
2. follow the instructions here: https://eksctl.io/usage/cluster-upgrade/
3. upgrade any daemonsets: https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html

**Comment by projectLewis** [comment]
I dont have the rights to do this one either.
```
Error: getting VPC configuration for cluster "operationcode-backend": describing CloudFormation stacks for "operationcode-backend": AccessDenied: User: -- (me) -- is not authorized to perform: cloudformation:ListStacks on resource:
```

**Comment by irvingpop** [comment]
Upgraded to 1.18 today
