### ISSUE TITLE
Create "application user" to manage data manipulation of DB on RDS safely

### ISSUE THREAD

**Issue by kylemh** [OperationCode/operationcode_infra#19]
In a bid to obfuscate roles properly and prevent unforeseen issues with a database owner running the show entirely, we're going to create an "application user" whose sole responsibility is the adding/deleting/editing of data in tables. It won't be able to edit relations, the schema, db user roles, and - most importantly - it will not be able to drop the database.

Unsure on this, but we may need to fix references to the proper db user in the backend, if utilized? @hpjaj @ohaiwalt - care to comment on that?

**Comment by ohaiwalt** [comment]
I'm going to close this, as it should be moved to the backend board
