### ISSUE TITLE
Move domain from DNSimple to Route 53

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode_infra#2]
Moves more of our infrastructure under AWS.

**Comment by ohaiwalt** [comment]
As a potential stretch on another task, creating a Terraform description of our DNS records under management would be a great step in allowing contributors to add infrastructure changes to other features.

Using AWS Route53 hosted zone resources and record resources, we could create an automated job to update DNS from GitHub.

**Comment by sethbergman** [comment]
Excellent :+1:

**Comment by sethbergman** [comment]
Possible solution:
https://github.com/kubernetes-incubator/external-dns
https://github.com/kubernetes-incubator/external-dns/blob/master/docs/tutorials/aws.md

**Comment by nellshamrell** [comment]
This looks like it is no longer and issue after adding hosted zones to Route53, but please feel free to re-open if you see further issues related to this.
