### ISSUE TITLE
Add a `POSTGRES_HOST` variable to backend deployment

### ISSUE THREAD

**Issue by ohaiwalt** [OperationCode/operationcode_infra#23]
This can be created preemptively until the backend actually supports it.

The operationcode_backend has its Postgres host hardcoded per environment, which makes it very difficult to create N number of environments for any given purpose.

**Comment by sethbergman** [comment]
This may be of use to you:
https://github.com/next-stack/stolon-chart/blob/master/stolon/templates/NOTES.txt

**Comment by ohaiwalt** [comment]
@sethbergman The issue is that the database host cannot be specified at runtime, as it's hardcoded. Can you expand on how that link would help?

**Comment by sethbergman** [comment]
I am not 100% sure, but the way the repo is setup seems to be the key. This may provide more clarity:
https://github.com/next-stack/stolon-chart/blob/master/stolon/README.md

**Comment by ohaiwalt** [comment]
Stolon, and particularly the Stolon Helm chart, are for running databases in containers, which is orthogonal to this issue. It doesn't matter where the database is running, we still need to be able to configure its hostname in in the application.

**Comment by sethbergman** [comment]
Ahh I see. Thank you for clarifying. I'm still learning HELM and kubernetes. :smiley:

**Comment by sethbergman** [comment]
It seems that there may be a solution here:
https://chat.stackexchange.com/rooms/56392/discussion-between-ypercube-and-davidechicco-it which is a continued discussion from this question:
https://dba.stackexchange.com/questions/168793/postgresql-what-is-the-hostname-address-of-my-default-database

**Comment by ohaiwalt** [comment]
@sethbergman you're overthinking it. This issue requests an environment variable be added to the `deployment.yml` file for the OpCode backend, in order for the backend application to make use of that to find its database. Very simple, 3-4 line change, would look like all the other environment variables present in the `deployment.yml`
