### ISSUE TITLE
Add a Kubernetes manifest to install Heapster

### ISSUE THREAD

**Issue by ohaiwalt** [OperationCode/operationcode_infra#26]
Adding Heapster will allow horizontal pod autoscaling, and support `kubectl top` commands.

Docs: https://github.com/kubernetes/heapster

The manifest should include a `Deployment` spec object at a minimum, plus whatever the documentation recommends.

**Comment by nellshamrell** [comment]
Let's do this post-migration.

**Comment by ohaiwalt** [comment]
Heapster is no longer recommended.
