### ISSUE TITLE
Suggestion: Use Helm for Ghost Installation

### ISSUE THREAD

**Issue by sethbergman** [OperationCode/operationcode_infra#27]
This chart bootstraps a Ghost deployment on a Kubernetes cluster using the Helm package manager.

It also packages the Bitnami MariaDB chart which is required for bootstrapping a MariaDB deployment for the database requirements of the Ghost application.

https://kubeapps.com/charts/stable/ghost

This is my suggestion rather that using a Digital Ocean instance.

**Comment by sethbergman** [comment]
Related config:
https://github.com/bitnami/bitnami-docker-ghost

**Comment by nellshamrell** [comment]
Upon talking with the infrastructure maintainers, we are not going to do this at this time, but thank you so much for the input, it's always good to think through these things.
