### ISSUE TITLE
Upgrade Tiller (Helm)

### ISSUE THREAD

**Issue by nellshamrell** [OperationCode/operationcode_infra#29]
We appear to be using an older version of Tiller (what runs on the server) with Helm (what runs on the workstation).  Our Tiller version is 2.6.2, while the latest is 2.7.2 - this includes a security fix https://github.com/kubernetes/helm/releases

**Comment by nellshamrell** [comment]
This may be fixed with the migration to the new Kubernetes cluster

**Comment by ohaiwalt** [comment]
New cluster: 
```$ helm version
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}```
