### ISSUE TITLE
Add a monitoring solution

### ISSUE THREAD

**Issue by nellshamrell** [OperationCode/operationcode_infra#30]
That will let us know when something is broken.

**Comment by desnudopenguino** [comment]
The TICK (https://www.influxdata.com/time-series-platform/) stack might be nice, or icinga2, or something similar. What sort of "broken" things are we trying to keep a pulse on?

**Comment by ohaiwalt** [comment]
Doing some work on this while streaming today

**Comment by ohaiwalt** [comment]
Prometheus is online in the monitoring namespace, but missing external cluster ingress and is unable to scrape kubelets due to missing APIServer webhooks. See [prereqs here](https://github.com/coreos/kube-prometheus#prerequisites).

**Comment by ohaiwalt** [comment]
Added the above prereqs, as well as recompiled https://github.com/coreos/kube-prometheus with kops support, and was able to get green across the board for monitoring targets. Items remaining include:

1.  Ingress resources for Prometheus
2. Ingress resources for Alertmanager
3. Ingress resources for Grafana
4. Wire a Slack webhook into the Alertmanager for critical alerts

Prior to this, we should make decisions around how to handle authentication and whether to seek to provide read-only dashboards and access.

**Comment by ohaiwalt** [comment]
Grafana is viewable anon at https://dashboards.operationcode.org.

Getting the generator code into a repository at some point will be good, but this works for now. Alertmanager is sending alerts to `#chatops` in the OpCode Slack.
