### ISSUE TITLE
Configure ActiveAdmin to be accessible in production

### ISSUE THREAD

**Issue by hpjaj** [OperationCode/operationcode_infra#38]
## Background

The backend has a [pending PR](https://github.com/OperationCode/operationcode_backend/pull/247) for the implementation of an admin dashboard using [ActiveAdmin](https://activeadmin.info/index.html).   

Everything works as desired locally, in development.  Meaning:

- both the front and backends run together seamlessly 
- the operation code website is accessible, as normal, via `http://localhost:4000/`
- the ActiveAdmin UI is accessible, as desired, via `http://localhost:3000/admin/login`

## Issue

When the backend PR has been merged to prod for a trial, visiting `https://operationcode.org/admin/login` yields a 404.  One idea is that the issue could be around the ports.  

In development, the backend runs on port 3000, and the frontend on port 4000.  ActiveAdmin runs off of Rails, on port 3000.

Perhaps we need some Docker (etc.) configuration, in order to work in prod?

## Resources

In the [ActiveAdmin Wiki](https://github.com/activeadmin/activeadmin/wiki), there is a tutorial on [Rails 5 API + ActiveAdmin + Create React App](https://medium.com/superhighfives/a-top-shelf-web-stack-rails-5-api-activeadmin-create-react-app-de5481b7ec0b), that might be helpful, as we also have a Rails API backend, with a separate React frontend.

This will likely need coordination/collaboration with the @OperationCode/back-end team at some point.

**Comment by hpjaj** [comment]
@ohaiwalt - No, it is not live in prod.

> You should be able to fairly trivially port forward to the pod to grab it. Is it possible to run it on a different port than 3000, or expose on a route within Rails?

¯\_(ツ)_/¯ Honestly I have tried everything I could think of to get it to work in prod.  It has to be infrastructure/platform related, at this point.  b/c everything works perfectly in development.

Hoping you all can get it across the finish line!

**Comment by ohaiwalt** [comment]
This is what was figured out last night, right? @hpjaj @nellshamrell 

Related to #43

**Comment by hpjaj** [comment]
@nellshamrell resolved this.  Closing.
