### ISSUE TITLE
Configure Cron Jobs 

### ISSUE THREAD

**Issue by hpjaj** [OperationCode/operationcode_infra#39]
## Background

We need to be able to have recurring cron jobs ran, on our behalf.  For example, to hit GitHub's API, or the Meetup API, on a daily basis, to pull in current statistics or Meetup events.

The [whenever gem](https://github.com/javan/whenever) is a perfect tool to solve this.  

The backend has a [pending PR](https://github.com/OperationCode/operationcode_backend/pull/257) to implement this gem; however, infrastructure related configuration will be required for it to work.

## Goal

Work with the backend team to implement the whenever gem, from an infrastructure perspective.

**Comment by nellshamrell** [comment]
I wonder if we could do this with a sidecar container.

**Comment by nellshamrell** [comment]
Useful info: https://stackoverflow.com/questions/41245076/how-can-i-run-a-cron-command-with-environmental-variables-set-by-kubernetes-secr

**Comment by desnudopenguino** [comment]
What sort of tasks need to be managed? If they aren't specific to server instances, you could set up a serverless cron job. From the looks of your code base, you use AWS for your stack, so an AWS Lambda hooked up to a CloudWatch event could handle such things.

**Comment by wimo7083** [comment]
We transitioned to using sidekiq-cron which doesn't require infrastructure work. You can safely close this.
