### ISSUE TITLE
Run everything through one load balancer

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode_infra#4]
Each service doesn’t need an LB. We currently have 3 load balancers for backend, frontend, bot. We would need another 3 for a staging site. ELBs are $20/mo ea. Using an Ingress controller, we can make that a single ELB, saving about $100/mo.

**Comment by ohaiwalt** [comment]
Definition of done:

Manifests for nginx Ingress controller deployment, service, configmap, as well as default-backend deployment and service. 

This should allow us to deploy the Ingress controller and begin creating Ingress resources for our applications.

**Comment by ohaiwalt** [comment]
Examples and documentation [here](https://github.com/kubernetes/ingress-nginx)
