### ISSUE TITLE
Create external traffic path to the OpCode backend for Admin panel

### ISSUE THREAD

**Issue by ohaiwalt** [OperationCode/operationcode_infra#43]
From here: https://operation-code.slack.com/archives/C83BJQ4KX/p1522632151000002

Definition of done:
- [ ] Add DNS record in DNSimple for admin.operationcode.org CNAME to the Kubernetes cluster Ingress load balancer
- [ ] Create `Ingress` resource that directs traffic on admin.operationcode.org to the backend service
- [ ] Verify with backend team that traffic is reaching appropriately

**Comment by nellshamrell** [comment]
Turns out we already have this set up with api.operationcode.org :D  Closing.
