### ISSUE TITLE
Make compute instances smaller

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode_infra#5]
Appropriately size the cluster to save some costs. Currently there's 6 instances (4 m3.larges ~$100/mo ea and 2 t2.nanos idk) that could be reduced to 6 instances of m3.mediums at ~$50/mo ea while increasing our cluster redundancy.

**Comment by ohaiwalt** [comment]
New Kubernetes cluster is created using t2.mediums, which run ~$34/mo.

I'll wait until I've added a clusterSpec to this repository to close this.

**Comment by nellshamrell** [comment]
This should be fixed with the new Kubernetes cluster.
