### ISSUE TITLE
Create a transition plan for new Front End

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/operationcode_infra#62]
In the near future @kylemh is going to be nearly finished with the @OperationCode/front-end project and we'll need the ability to test deploys and an easy way to switch over instance in the front end. 

I'm not sure if this should be done at the kube deployment.yaml file, or done within the application deploy scripts. Our issue right now within the deployment scripts is that we promote any push to master to production. So when we activated these scripts we'd have to work on a secondary branch.

**Comment by ohaiwalt** [comment]
@kylemh have you already thought this one through? Do you have something written up, since you said you're targeting Monday?

**Comment by kylemh** [comment]
I honestly don't know what's involved.

I was assuming we could still manage infrastructure for the back-end, drop the front-end from the load balancer, and then I'd hijack DNS via Now.sh and our registrar/domain service.

**Comment by wimo7083** [comment]
Closing this since the transition plan has been figured out and we are doing it now.
