### ISSUE TITLE
Missing dockerhub credentails

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/operationcode_infra#64]
The only source of our credentials are stored encrypted within travis, we cannot copy them over and we need to do a password reset and then update the credentials into our secure storage in a way that allows us to add new projects in the future.

Right now this means that if we want to use containers, we have to either create a new account, or use ECR. Both of these mean giving individuals more access to assets which we are doing out of convenience but why not just fix the issue and limit prod and asset access.

1. Reset creds in dockerhub
2. Get new creds and store into 1PW
3. Update creds within frontend, backend and new frontend. 
4. Incorporate other projects to use dockerhub instead of ECR.

**Comment by ohaiwalt** [comment]
Sent a query to DockerHub support around recovering the `operationcode` user.

**Comment by ohaiwalt** [comment]
No response from DockerHub. Not even an automated email :(

**Comment by ohaiwalt** [comment]
After reaching out on Twitter, I got these credentials reset today. They've been added to 1Password, and updated the `operationcode_backend` and `operationcode_frontend` repos in Travis.
